const titles = {
  eng: [
    "Hi!",
    "Happy birthday!",
    "Happy New Year!",
    "Happy holiday!",
    "How're you doing?",
    "Congratulations!",
    "For no reason",
    "It's for you",
    "Keepsake",
    "Good luck",
    "Don't be angry",
    "Don't be bored",
    "Be my friend",
    "I miss you",
    "I love you!",
    "Marry me",
    "Come back",
    // "Your text",
  ],
  rus: [
    "Привет!",
    "С днем рождения!",
    "С Новым Годом!",
    "С праздником!",
    "Как дела?",
    "Поздравляю!",
    "Просто так",
    "Это тебе",
    "На память",
    "Всего хорошего",
    "Удачи!",
    "Всего самого хорошего",
    "Не сердись",
    "Не скучай",
    "Давай дружить",
    "Я по тебе скучаю",
    "Я тебя люблю!",
    "Давай поженимся",
    "Вернись!",
    // "Твой текст",
  ],
};

export default titles;
